### ISSUE TITLE
duplicate metrics with same path

### ISSUE THREAD

**Issue by MansuyDavid** [loyispa/jgc_exporter#122]
I have duplicate metrics with the same path : 

> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_MFC1.log",host="DMAMV-APP01",} 5.283774464E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_CRON1.log",host="DMAMV-APP01",} 1.429209088E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_CRON1.log",host="DMAMV-APP01",} 1.2845056E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_CRON1.log",host="DMAMV-APP01",} 1.372585984E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_CRON1.log",host="DMAMV-APP01",} 1.27926272E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_MFC1.log",host="DMAMV-APP01",} 5.028970496E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_GUI1.log",host="DMAMV-APP01",} 5.574230016E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_GUI1.log",host="DMAMV-APP01",} 4.867489792E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_CRON1.log",host="DMAMV-APP01",} 1.22683392E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_CRON1.log",host="DMAMV-APP01",} 1.422917632E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_CRON1.log",host="DMAMV-APP01",} 1.369440256E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_CRON1.log",host="DMAMV-APP01",} 1.404043264E9
> jgc_heap_occupancy_before_collection_bytes{path="D:\\PROD\\gc\\gc_AMQ.log",host="DMAMV-APP01",} 3.031433216E9

This happend when the file are rotated, and GC continue to write in the original file. (I'm using WindowsTailer but it should be the same for Unix)
Because when file rotate (TailerManager.java) : 
```java
                    } else if (tailer.rotated()) {
                        try {
                            rotate(tailer); //here
                        } finally {
                            iterator.remove(); //file is removed from TailerManager.registry.
                        }
                    }
```
file is removed from TailerManager.registry.
and the rotate method : 
```java
    private void rotate(Tailer tailer) {
        try {
            tailer.close();
        } finally {
            try {
                listener.onRotate(tailer.getFile()); //here
            } catch (Throwable t) {
                LOG.error("Rotate file failed: {}", tailer, t);
            }
        }
    }
```
and then the GCEventHandlerManager.onRotate() : 
```java
    @Override
    public void onRotate(File file) {
        // not clean metric
        registry.remove(file); //file is removed from GCEventHandlerManager.registry
        LOG.info("Rotate file: {}", file);
    }
```
the file is removed from GCEventHandlerManager.registry.  
Because of that, when the file is matched again (in TailerManager) : 
```java
for (File file : matchingFiles) {
                    try {
                        registry.computeIfAbsent(
                                file,
                                f -> {
                                    listener.onOpen(file);
                                    return newTailer(
                                            f, true, batchSize, bufferSize, linesPerSecond);
                                });
                    } catch (UnsupportedOperationException ignore) {
                        LOG.warn("Ignore unsupported file: {}", file);
                    } catch (Throwable t) {
                        LOG.error("Watch file error: {}", file, t);
                        invalidFiles.put(file, System.currentTimeMillis());
                    }
                }
```
file is not in the TailerManager.registry, so it compute GCEventHandler.onOpen(file);
```java
    @Override
    public void onOpen(File file) {
        registry.computeIfAbsent(file, f -> new GCEventHandlerMatcher(file).find());
        LOG.info("Register file: {}", file);
    }
```
file is not in the GCEventHandlerManager so it compute new GCEventHandlerMatcher(file).find().  
which return a new instance of AbstractJVMEventHandler (for example classic), which will use metrics like that : 
```java
HEAP_OCCUPANCY_BEFORE_COLLECTION
.attach(this, path, host)
.set(heapSummary.getOccupancyBeforeCollection() * 1024);
```
And use "this", which will create a new Metric, but with same path and host than previous file.

So my question is, **why do we want to close file when rotated ?**
No matter if inode changes or if file is truncated, I think we must reset the "raf" to the begining of the file, and keep doing next readings normally.
Moreover, 
1. there is no chance that gc type has changed (G1, ZGC, Classic...) during rotation.
2. if logs are truncated in a middle of an "event", re using the same "diary" will allow to get the complete event to be treated by GCToolkit. (maybe?)

I will propose a pull request with that solution we will be able to discuss on that with real code.

**Comment by loyispa** [comment]
Thanks for the bug report.  I haven't carefully reviewed the code yet , but the bug should be fixed by previous PRs.  Could you build from  the latest commit?

So my question is, why do we want to close file when rotated ?
------------------------
Because we may change the gc type sometimes. For the example, we restart the server and change the garbage collector from cms to G1,  so we need to **recognize** the change.   There should  be more elegant and efficient ways, but current solution is the simplest way to acheive that.  Are you willing to improve it?  I am very happy to discuss how to improve it.

**Comment by loyispa** [comment]
Is the solution for dumlicate metrics?  The issue should have be fixed.  @MansuyDavid

**Comment by MansuyDavid** [comment]
will be tested on last revision, this should solve the issue.
