### ISSUE TITLE
jgc_exporter exposes no metric for my GC log file

### ISSUE THREAD

**Issue by greg-junkietech** [loyispa/jgc_exporter#61]
I let jgc_exporter run using command `%JAVA_HOME%\bin\java -jar jgc_exporter_v0.3.0.jar config.yml`, given a simple config.yml containing `fileRegexPattern: gc\.log` and this [gc.log](https://github.com/loyispa/jgc_exporter/files/13920850/gc.log) file (obtained from a java process started with options `-Xlog:gc*:file=gc.log:time,tags` under `openjdk version "11.0.15" 2022-04-19`) that looks like the test resource [zgc.log](https://github.com/loyispa/jgc_exporter/blob/main/src/test/resources/parser/zgc.log).

jgc_exporter does not expose more than these 2 metrics:
```
# HELP jgc_collect_files jgc_collect_files
# TYPE jgc_collect_files gauge
# HELP jgc_exporter_version_info The version of jgc_exporter
# TYPE jgc_exporter_version_info gauge
jgc_exporter_version_info{version="0.3.0",} 1.0
# HELP jgc_startup_timestamp_seconds Timestamp of exporter startup
# TYPE jgc_startup_timestamp_seconds gauge
jgc_startup_timestamp_seconds 1.705072929264E9
```
The console where jgc_exporter runs shows only this:
```
2024-01-12 16:22:09,033 INFO  [main] prometheus.exporter.jgc.Bootstrap:68  -     _                                          _
   (_) __ _  ___     _____  ___ __   ___  _ __| |_ ___ _ __
   | |/ _` |/ __|   / _ \ \/ / '_ \ / _ \| '__| __/ _ \ '__|
   | | (_| | (__   |  __/>  <| |_) | (_) | |  | ||  __/ |
  _/ |\__, |\___|___\___/_/\_\ .__/ \___/|_|   \__\___|_|
 |__/ |___/    |_____|       |_|
                                                  0.3.0
```

What is jgc_exporter supposed to expose?
Am I doing something wrong?

**Comment by loyispa** [comment]
Please attach your gc log.  From your description, It seems most like the exporter didn't find your log.  Please set fileRegexPattern **absolute path** and try . If exporter recognizes the log , it will log:
```
2024-01-13 11:01:05,243 INFO  [tail-watcher] prometheus.exporter.jgc.collector.GCCollector:54  - Register gc log: /Users/loyispa/Desktop/gc.log
```

**Comment by greg-junkietech** [comment]
You can download my **gc.log** from my previous comment.

I let it run on Windows and it makes no difference whether setting `fileRegexPattern` with `gc.log`, `gc\.log` or even with absolute path `c:\Temp\gc.log` or `c:\\Temp\\gc\.log`: it just does not log any registration nor publish any metric.

**Comment by loyispa** [comment]
Sorry @greg-junkietech,  the exporter does not yet support Windows. I will consider adding it.

**Comment by greg-junkietech** [comment]
Oh nice, thanks, do you know when approximately?

**Comment by loyispa** [comment]
@greg-junkietech  I guess within the next two weeks, at that time i will release the v0.4.0.

**Comment by greg-junkietech** [comment]
@loyispa please let me know when it is released

**Comment by loyispa** [comment]
@greg-junkietech  development is almost done and we will let you know as soon as it is complete.

**Comment by loyispa** [comment]
@greg-junkietech  Windows is already available.

**Comment by greg-junkietech** [comment]
@loyispa I wanted to give v0.4.1 a try, compiled it and tried again (`%JAVA_HOME%\bin\java -jar jgc_exporter_v0.4.1.jar config.yml`), unfortunately without success so far.

With `config.yml` just containing the line `fileRegexPattern: C:\\Temp\\gc\.log` and this 
[C:\Opt\Temp\gc.log](https://github.com/loyispa/jgc_exporter/files/14344319/gc.log), the log does contain not more than that (similar to attempt above with v0.3.0):
```
2024-02-20 11:56:27.086 [main] INFO  prometheus.exporter.jgc.Bootstrap:74 -- 
    _                                          _            
   (_) __ _  ___     _____  ___ __   ___  _ __| |_ ___ _ __ 
   | |/ _` |/ __|   / _ \ \/ / '_ \ / _ \| '__| __/ _ \ '__|
   | | (_| | (__   |  __/>  <| |_) | (_) | |  | ||  __/ |   
  _/ |\__, |\___|___\___/_/\_\ .__/ \___/|_|   \__\___|_|   
 |__/ |___/    |_____|       |_|                            
                                                  0.4.1

```
and the process looks to be hanging, see [jstack.txt](https://github.com/loyispa/jgc_exporter/files/14344009/jstack.txt).

The endpoint http://localhost:5898/metrics does still expose the same information:
```
# HELP jgc_startup_timestamp_seconds Timestamp of exporter startup
# TYPE jgc_startup_timestamp_seconds gauge
jgc_startup_timestamp_seconds{host="shw-ch-vlep321",} 1.708426587271E9
# HELP jgc_exporter_version_info The version of jgc_exporter
# TYPE jgc_exporter_version_info gauge
jgc_exporter_version_info{version="0.4.1",host="shw-ch-vlep321",} 1.0
```

Am I doing something wrong?

**Comment by loyispa** [comment]
```
With config.yml just containing the line fileRegexPattern: C:\\Temp\\gc\.log and this
[C:\Opt\Temp\gc.log](https://github.com/loyispa/jgc_exporter/files/14344319/gc.log), the log does contain not more than that (similar to attempt above with v0.3.0):
```

Also, please ensure which one is the true path of gc log,   *C:\Opt\Temp\gc.log*   or   *C:\\Temp\\gc.log* ?

**Comment by greg-junkietech** [comment]
I get the same with `fileGlobPattern: C:\\Temp\\gc.log`

**Comment by loyispa** [comment]
Is the log constantly updated?   The exporter will only consume from the latest log line after recognizing the file for the first time.

**Comment by greg-junkietech** [comment]
alright, looks much better and promising with live data, thank you very much
issue can be closed IMO
