### ISSUE TITLE
gc files are not closed between reading so JMV can not roll gc files as expected

### ISSUE THREAD

**Issue by MansuyDavid** [loyispa/jgc_exporter#90]
Hello,

I use your tool on Windows (I changed the inode object and method in Tailer.java to allow my windows file to be identified by a "null" inode value. it's ugly but it works for my needs, windows files are read as expected)

I have a problem (which I don't think is related to my "windows modifications"),
In Tailer.java we use a RandomAccessFile (raf), which is not closed until the file is considered "idle", So the file is considered as "in use" by windows, which doesn't allow renaming the file (when the JVM want to roll the logs or if I do that manually myself).
This cause other problem when gc files doesn't roll when needed.

I don't know if it is the same for Linux/Unix plateform.

Any way, I think I will modify my fork, to close the raf at the end of Tailer.readLines() (and save the raf.getFilePointer() position).
When next readLines() will be called, I will first compare the size of the file and the saved filePointer position.
If  equal, then return empty list.
if superior, then I create a new RandomAccessFile instance, and seek to the last saved filePointer position.

With this, probability that the file is "locked" by jgc_exporter when JVM want to roll the file will be much much less.

If you are interested, I will propose that in a future pull request.
If you have an other point a view than mine, I will be happy to discuss.

**Comment by loyispa** [comment]
@MansuyDavid  PRS are always welcome :) 

```
I use your tool on Windows (I changed the inode object and method in Tailer.java to allow my windows file to be identified by a "null" inode value. it's ugly but it works for my needs, windows files are read as expected)
```
I have my doubts about that if a dummy innode is always returned, how do we know the log is indeed rotated/moved? Have you tested log rotation in your way?

```
When next readLines() will be called, I will first compare the size of the file and the saved filePointer position.
If equal, then return empty list.
```
It is indeed a feasible way to bypass the windows restrictions, until we find a more suitable solution, we can do this.

**Comment by MansuyDavid** [comment]
When log rotate, with my modifications, A "new" file is registered, but because this rotated files will never be updated, this doesn't create any metrics. (because when we create the RAF we move pointer to end of file, so only added content will be read => so nothing).

current file is never considered as "rotated" be cause we never pass in this condition : 
```java
if (currInode != inode) {
    LOG.info("{} rotated: inode changed", this.file);
    return true;
}
```

But it will be considered as truncated : 
```java
            // truncate occurs
            long fp = raf.getFilePointer();
            long len = raf.length();
            if (fp > len) {
                LOG.info("{} rotated: file truncated", this.file);
                return true;
            }
```

so current file will be removed from watch list, but added at next findMachingFiles(), so 30 seconds, and then, read again normally.
So maybe I loose 30 seconds of metrics, but I accept this lost as a tradeoff for a very simple modification of code 😉 .

Ok for the PRs, I will work on that then.
